#!/bin/bash

print_info() {
    local total_folders="$1"
    local top_folders="$2"
    local total_files="$3"
    local config_files="$4"
    local text_files="$5"
    local executable_files="$6"
    local log_files="$7"
    local archive_files="$8"
    local symbolic_links="$9"
    local top_files="${10}"
    local top_executable_files="${11}"
    local execution_time="${12}"

    echo "Total number of folders (including all nested ones) = $total_folders"
    echo "TOP 5 folders of maximum size arranged in descending order (path and size):"
    echo "$top_folders"
    echo "Total number of files = $total_files"
    echo "Number of:"
    echo "Configuration files (with the .conf extension) = $config_files"
    echo "Text files = $text_files"
    echo "Executable files = $executable_files"
    echo "Log files (with the extension .log) = $log_files"
    echo "Archive files = $archive_files"
    echo "Symbolic links = $symbolic_links"
    echo "TOP 10 files of maximum size arranged in descending order (path, size and type):"
    echo "$top_files"
    echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file)"
    echo "$top_executable_files"
    echo "Script execution time (in seconds) = $execution_time"
}
